apiVersion: v1
kind: Service
metadata:
  name: {{ include "microsite.fullname" . }}-lb
spec:
  selector:
    app: {{ include "microsite.fullname" . }}
  ports:
  - port: 8081
    targetPort: 80
  type: LoadBalancer
