apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.mysql.name }}-azure-managed-disk-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.mysql.name }}-managed-premium-retain-sc
  resources:
    requests:
      storage: 1Gi     