apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.mysql.name }}-dbcreation-script
data: 
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS quizdb;
    CREATE DATABASE quizdb; 