apiVersion: v2
name: space-quiz
description: Umbrella Helm chart for quiz Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: quiz-database
    version: 1.0.0
  - name: quiz-filestorage
    version: 1.0.0
  - name: quiz-microsite
    version: 1.0.0
  - name: quiz-service
    version: 1.0.0