trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - /cluster-config/aks/*

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  service_connection: ARM_SERVICE_CONNECTION
  kubernetesServiceConnection: "spaceaks"
  k8sNamespace: "default"

stages:
  - stage: Dev
    jobs:
      - job: EnvironmentConfig
        steps:
          - task: KubernetesManifest@0
            displayName: Create Dev NameSpace
            inputs:
              action: deploy
              namespace: $(k8sNamespace)
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              manifests: |
                $(System.DefaultWorkingDirectory)/cluster-config/aks/manifests/dev/01-namespace.yml
          - task: KubernetesManifest@0
            displayName: Deploy Ingress Resources
            inputs:
              action: deploy
              namespace: dev
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              manifests: |
                $(System.DefaultWorkingDirectory)/cluster-config/aks/manifests/dev/02-space-ingress-host-dns-root-ssl.yml
                $(System.DefaultWorkingDirectory)/cluster-config/aks/manifests/dev/03-space-ingress-host-dns-cpr-ssl.yml
  - stage: Qa
    dependsOn:
      - Dev
    jobs:
      - job: EnvironmentConfig
        steps:
          - task: KubernetesManifest@0
            displayName: Create Qa NameSpace
            inputs:
              action: deploy
              namespace: $(k8sNamespace)
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              manifests: |
                $(System.DefaultWorkingDirectory)/cluster-config/aks/manifests/qa/01-namespace.yml
          - task: KubernetesManifest@0
            displayName: Deploy Ingress Resources
            inputs:
              action: deploy
              namespace: qa
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              manifests: |
                $(System.DefaultWorkingDirectory)/cluster-config/aks/manifests/qa/02-space-ingress-host-dns-root-ssl.yml
                $(System.DefaultWorkingDirectory)/cluster-config/aks/manifests/qa/03-space-ingress-host-dns-cpr-ssl.yml
