apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Namespace }}-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Namespace }}-{{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: spacedevacr.azurecr.io/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_Quiz_service
              value: quiz-service