apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Namespace }}-{{ .Release.Name }}
  ports:
  - port: 80
    targetPort: 80
