apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-lb
spec:
  selector:
    app: {{ .Release.Namespace }}-{{ .Release.Name }}
  ports:
  - port: 8081
    targetPort: 80
  type: LoadBalancer
