apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.mysql.name }}-azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Release.Namespace }}-{{ .Values.mysql.name }}-azurefile-sc
  resources:
    requests:
      storage: 1Gi
