# schedules:
#   - cron: "0 0 * * *"
#     displayName: Daily midnight build
#     branches:
#       include:
#         - main

pr: none

trigger: none
schedules:
  - cron: "11 8 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master
    always: true

pool:
  vmImage: ubuntu-latest

variables:
  - name: service_connection
    value: ARM_SERVICE_CONNECTION

steps:
  - checkout: self
  - task: AzureCLI@2
    displayName: Stop Cluster
    inputs:
      azureSubscription: $(service_connection)
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: |
        az aks stop --name space-dev-aks-cluster --resource-group space-dev-rg-aks
