apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "database.fullname" . }}-managed-premium-retain-sc
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain # Default is Delete, recommended is retain
volumeBindingMode: WaitForFirstConsumer # Default is Immediate, recommended is WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  storageaccounttype: {{ .Values.storageClass.accountType }}   # or we can use Standard_LRS
  kind: managed # Default is shared (Other two are managed and dedicated)
