apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "database.fullname" . }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ include "database.fullname" . }}-managed-premium-retain-sc
  resources:
    requests:
      storage: {{ .Values.volume.storage }}