apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-secret
type: Opaque
data:
  db-username: {{ .Values.secret.mysql_username | b64enc | quote }}
  db-password: {{ .Values.secret.mysql_password | b64enc | quote }}