apiVersion: v1
kind: Service
metadata: 
  name: {{ include "database.fullname" . }}
spec:
  selector:
    app: {{ include "database.fullname" . }}
  ports: 
    - port: 3306  
  clusterIP: None # This means we are going to use Pod IP    